parameters:
#    awhs_task.example.class: AWHS\TaskBundle\Example

services:
#    awhs_task.example:
#        class: %awhs_task.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
